=== matejsvarc/KIProjekt/www/html/zapisy/validace/tymy.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tymy">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tym" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="nazev" type="xs:string"/>
                            <xs:element name="datum_zalozeni" type="xs:date"/>
                            <xs:element name="mesto" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== matejsvarc/KIProjekt/xml_test/tymy.xml
<tymy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="tymy.xsd">
    <tym>
        <nazev>Los Angeles Lakers</nazev>
        <datum_zalozeni>1947-01-01</datum_zalozeni>
        <mesto>Los Angeles</mesto>
    </tym>
    <tym>
        <nazev>Miami Heat</nazev>
        <datum_zalozeni>1988-04-22</datum_zalozeni>
        <mesto>Miami</mesto>
    </tym>
    <tym>
        <nazev>Golden State Warriors</nazev>
        <datum_zalozeni>1946-04-25</datum_zalozeni>
        <mesto>San Francisco</mesto>
    </tym>
    <tym>
        <nazev>Chicago Bulls</nazev>
        <datum_zalozeni>1966-01-26</datum_zalozeni>
        <mesto>Chicago</mesto>
    </tym>
    <tym>
        <nazev>Boston Celtics</nazev>
        <datum_zalozeni>1946-06-06</datum_zalozeni>
        <mesto>Boston</mesto>
    </tym>
</tymy>
